//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetMessenger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    
        public virtual int spAddUser(string name, string hash)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var hashParameter = hash != null ?
                new ObjectParameter("Hash", hash) :
                new ObjectParameter("Hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddUser", nameParameter, hashParameter);
        }
    
        public virtual int spAddUser1(string name, string hash)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var hashParameter = hash != null ?
                new ObjectParameter("Hash", hash) :
                new ObjectParameter("Hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddUser1", nameParameter, hashParameter);
        }
    
        public virtual int spSendMessage(string sender, string reciever, string messageText, Nullable<System.DateTime> sendTime)
        {
            var senderParameter = sender != null ?
                new ObjectParameter("Sender", sender) :
                new ObjectParameter("Sender", typeof(string));
    
            var recieverParameter = reciever != null ?
                new ObjectParameter("Reciever", reciever) :
                new ObjectParameter("Reciever", typeof(string));
    
            var messageTextParameter = messageText != null ?
                new ObjectParameter("MessageText", messageText) :
                new ObjectParameter("MessageText", typeof(string));
    
            var sendTimeParameter = sendTime.HasValue ?
                new ObjectParameter("SendTime", sendTime) :
                new ObjectParameter("SendTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSendMessage", senderParameter, recieverParameter, messageTextParameter, sendTimeParameter);
        }
    
        public virtual ObjectResult<spShowMessages_Result> spShowMessages(string reciever)
        {
            var recieverParameter = reciever != null ?
                new ObjectParameter("Reciever", reciever) :
                new ObjectParameter("Reciever", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spShowMessages_Result>("spShowMessages", recieverParameter);
        }
    }
}
